---
title: "Imputation of incomplete multilevel data"
author: "Hanne Oberman"
format: html
---

# Outline

- motivation and intended audience
- the mice framework/package
- background info on missingness mechanisms etc.
- case study

# Intended audience

This tutorial aims to serve analysts who know their way around multilevel modeling, but are not (as) familiar with missing data imputation.

# Introduction
In scientific research it is common to draw conclusions from data. In many cases, however, the available information may not be sufficient to arrive at the correct conclusion. This is a common scenario and extends far beyond the domain of missing values in data sets. In any case, when the available information is not sufficient, we need to apply some modeling to arrive at the correct conclusion. 

First and foremost, the best way to deal with unavailble information is to make sure that you have none. This is in itself impossible to attain, as one would need the potentially unavailable information to definitively prove that there is no deviation from the conclusions obtained on the available information. Since this is impossible to prove in practice, it is far easier to assume that we can use some modeling based on the available information to arrive at the correct conclusion.

In such modeling methods, there are three possible scenarios. 

## Scenario 1: Missingness is not data dependent
The first scenario is that analysis of the available information itself yields the correct conclusion. This is an ideal scenario, but it is most likely not the case. Rubin (1987) defines this scenario as **missing completely at random** (MCAR). Hand (2020) defines this - perhaps more intuitively - as *not data dependent*. There is, however, a caveat with Hand's terminology as *data dependent* may lull the analyst into the false sense of security of assuming that the available data is all data. Because we would like to explicitly highlight the possibility that more data is always available, and that not considering this data may lead to incorrect conclusions, we favor the explicit use of the term *missingness* in Rubin's terminology.  Therefore, we'd like to stick with Rubin's MCAR. 

With MCAR, the missingness in the data is unrelated to any observed information (i.e. data points), nor to any unobserved information. In terms of classical statistics, this would mean that a random and sufficient sample from a population would be randomly incomplete in such a way that analysis of the incomplete data would yield a sufficient statistic. You may recognize this as the age-old adage *"the sample is representative of the population"*, but now the sample is both representative and incomplete. The bottom line is that we can ignore the two missingness mechanisms that are at play here:

1. First, the population has been sampled, meaning that the information that we have obtained is incomplete. Random sampling makes this mechanism ignorable and analyzing a sufficiently large sample data will - in the limit - yield the same conclusion as analyzing the population itself. 
2. Second, the sample is now incomplete. This incompleteness is also assumed to be random and thereby ignorable. In other words, we have merely obtained a smaller sample of the information than originally would have been intended. But analyzing this sample, given that it is still sufficiently large, will still yield the same conclusion as analyzing the population. 

In terms of probability we could argue that with MCAR, the probability to be observed is the same for every obtained sequence of information. The complement, however, must also hold: the probability to be unobserved is the same for every unobtained sequence of information. We would like to note that this is a very strong assumption and is often not met in practice. We would also like to note that for structured data this does not mean that every cell has an equal probability to be unobserved. The distribution of random probabilities may change between columns in the data, for example, whilst still being fully random. But as long as this distribution is not related to the sampling, we can still assume that the data is MCAR.

## Scenario 2: Missingness is observed data dependent
This assumption is violated when the probability of being unobserved - or observed, for that matter - is dependent on more than one dimension in the available information. For example when the probability of being unobserved is dependent on the value of another variable in the data, we have a clear and proven deviation from MCAR. This would bring us to the second scenario: **missing at random (MAR)** (Rubin, 1976). With MAR the observed information holds the key to unlocking the missing information. In Hand's terminology, this would be *seen data dependent*. The difficulty here is that - unlike with MCAR, where the missingness mechanism may not be dependent on any observed nor unobserved data - with MAR, it may only be observed data dependent. 

The observed data dependency of MAR is very flexible assumption. It allows us to model the unobserved information based on the observed information. In simple terms, if we define a model for all unobserved information, based on all observed information and combine that model with the observed data model, we'd be able to draw correct conclusions. Bayesians would recognize this as a form of conditional probability, where the probability of the unobserved information is conditional on the observed information. Specifying a good prior for the unobserved information is crucial here, as it will determine the outcome of the model. Any sufficient prior will yield a correct posterior predictive distribution and, hence, a correct conclusion. The flexibility in the Bayesian approach is that it allows for straightforward seperation of the missingness and analysis problems for any scenario that is MAR.

## Scenario 3: Missingness is not data dependent
But what if your missingness is related to the data that you cannot see? This would mean that no matter what type of analysis you perform on the observed information, your conclusions would be invalid. This is the third scenario: **missing not at random (MNAR)** (Rubin, 1976). Hand (2020) defines this as *unseen data dependent*. This is the most difficult scenario to deal with, as it is impossible to model the missing information based on the observed information alone and some form of *adjustment* is needed to arrive at the correct conclusion.

::: {.callout-info}
# why not distinguish between missingness mechanisms
explanation needed
:::

1. missing data occur often in data with human subjects
2. missing data may be resolved, but need to be handled in accordance with the analysis of scientific interest
3. in human-subjects research, there is often clustering, which may be captured with multilevel modeling techniques
4. if the analysis of scientific interest is a multilevel model, the missing data handling method should accommodate the multilevel structure of the data
4. both missingness and multilevel structures require advanced statistical techniques
5. this tutorial sets out to facilitate empirical researchers in accommodating both multilevel structures as well as missing data
6. we illustrate the use of the software by means of a case study

# Methods

The [R]{.proglang} package [mice]{.pkg} provides a framework for imputing incomplete data on a variable-by-variable basis. The [mice]{.fct} function allows users to flexibly specify how many times and under what model the missing data should be imputed. This is reflected in the first four function arguments

```r
mice(data, m, method, predictorMatrix, ...)
```

where `data` refers to the incomplete dataset, `m` determines the number of imputations, `method` denotes the functional form of the imputation model and `predictorMatrix` specifies the interrelational dependencies between variables and imputation models (i.e., the set of predictors to be used for imputing each incomplete variable).


# References

<!-- FIMD, section 7.10 -->

<!-- > Recipe for a level-1 target:  -->
<!-- 1.	Define the most general analytic model to be applied to imputed data;  -->
<!-- 2.	Select a 2l method that imputes close to the data;  -->
<!-- 3.	Include all level-1 variables;  -->
<!-- 4.	Include the disaggregated cluster means of all level-1 variables;  -->
<!-- 5.	Include all level-1 interactions implied by the analytic model;  -->
<!-- 6.	Include all level-2 predictors;  -->
<!-- 7.	Include all level-2 interactions implied by the analytic model;  -->
<!-- 8.	Include all cross-level interactions implied by the analytic model;  -->
<!-- 9.	Include predictors related to the missingness and the target;  -->
<!-- 10.	Exclude any terms involving the target -->

<!-- > Recipe for a level-2 target:  -->
<!-- 1.	Define the most general analytic model to be applied to imputed -->
<!-- data;  -->
<!-- 2.	Select a 2lonly method that imputes close to the data;  -->
<!-- 3.	Include the cluster means of all level-1 variables;  -->
<!-- 4.	Include the cluster means of all level-1 interactions;  -->
<!-- 5.	Include all level-2 predictors;  -->
<!-- 6.	Include all interactions of level-2 variables;  -->
<!-- 7.	Include predictors related to the missingness and the target;  -->
<!-- 8.	Exclude any terms involving the target -->
